services:
  db:
    image: postgres:15
    container_name: taekwondo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: taekwondo
      POSTGRES_PASSWORD: taekwondo
      POSTGRES_DB: taekwondo_db
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
